### ISSUE TITLE
Research suitable platform for Adopt A Coin

### ISSUE THREAD

**Issue by FullstackGJJ** [Fellowship-of-Pawgrammers/adopt-a-coin#1]
This is where we want to put our research finding and proposals for suitable platform for our pet adoption cryptocurrency

**Comment by FullstackGJJ** [comment]
One candidate: https://moonbeam.network/

The website looks cool

**Comment by mjluck** [comment]
And cool looking websites are best websites

**Comment by FullstackGJJ** [comment]
All in favor of using https://moonbeam.network/, say aye and heart vote this comment.

**Comment by mjluck** [comment]
Does that mean we win

**Comment by FullstackGJJ** [comment]
Yes
